name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Hangi branch'e push atınca çalışsın?

env:
  PROJECT_ID: senin-google-cloud-proje-id-buraya # Burayı kendi ID'inle değiştir
  SERVICE_NAME: senin-servis-ismin # Cloud Run'da görünecek isim
  REGION: europe-west1 # Sunucu konumu (örn: Belçika)

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Google Cloud'a Giriş Yap
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # Cloud Run'a Deploy Et (Source Deploy Yöntemi)
      - name: Deploy to Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          source: . # Kodun olduğu dizin (Dockerfile varsa onu kullanır, yoksa otomatik algılar)
          project_id: ${{ env.PROJECT_ID }}
          # Eğer SQL bağlantısı varsa env vars buraya eklenecek, aşağıda anlattım.